project:
  title: "My Website"
  type: schema
  resources:
    - CNAME

website:
  title: "Kai Prince"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: papers/research.qmd
        text: "Research Output"
      - href: teaching.qmd
        text: "Teaching Activities"
      - href: advocacy.qmd
        text: "Advocacy Work"
      - href: automations.qmd
        text: "Automations"
    right:
      - about.qmd

format:
  schema-html:
    css: styles.css
    comments:
      hypothesis: true
    respect-user-color-scheme: true
    email-obfuscation: javascript
    theme:
      - cosmo
      - brand

execute:
  freeze: auto
  cache: true

bibliography: references.bib
csl: harvard-manchester.csl
link-citations: true