project:
  title: "My Website"
  type: schema
  resources:
    - CNAME

website:
  title: "Kai Prince"
  navbar:
    logo: images/kai-prince.jpg
    logo-alt: "A picture of Kai Prince"
    left:
      - href: activities.qmd
        text: "Activities"
    right:
      - about.qmd
  repo-url: https://github.com/kai-prince-sfhea/kai-prince-sfhea.github.io
  repo-actions: [source, issue]
  reader-mode: true
  draft-mode: visible
  site-url: https://kaiprince.co.uk
  google-analytics: G-0QRFD5NB5R

format:
  schema-html:
    css: styles.css
    comments:
      hypothesis: true
    respect-user-color-scheme: true
    email-obfuscation: javascript
    theme:
      - cosmo
      - brand

execute:
  freeze: auto
  cache: true

csl: harvard-manchester.csl
link-citations: true

callouty-theorem:
  thm:
    override-title: false
    callout:
      type: important
      appearance: minimal
  lem:
    override-title: false
    callout:
      type: warning
      appearance: minimal
  prp:
    override-title: false
    callout:
      type: note
      appearance: minimal
  exr:
    override-title: false
    callout:
      type: caution
      appearance: minimal
  proof:
    override-title: true
    callout:
      type: tip
      appearance: default
      collapse: true
      icon: false
  solution:
    override-title: true
    callout:
      type: tip
      appearance: default
      collapse: true
      icon: true
  remark:
    override-title: true
    callout:
      type: tip
      appearance: default
      collapse: false
      icon: true

  # theorems types not specified in the metadata will be rendered as is
  cor: default # calloutify corollaries with default style
  def:
    override-title: false
    callout: 
      type: note
      appearance: minimal # also support default style here