project:
  title: "My Website"
  type: website
  resources:
    - CNAME
    - "*.json"
  pre-render: math-macros.py

website:
  title: "Kai Prince"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: research.qmd
        text: "Research Output"
      - href: teaching.qmd
        text: "Teaching Activities"
      - href: advocacy.qmd
        text: "Advocacy Work"
      - href: automations.qmd
        text: "Automations"
    right:
      - about.qmd

format:
  html:
    comments:
      hypothesis: true
    respect-user-color-scheme: true
    html-math-method:
      method: mathjax
      url: "https://cdn.jsdelivr.net/npm/mathjax@4.0.0-beta.7/tex-mml-chtml.js"
    email-obfuscation: javascript
    include-in-header: mathjax.html
    theme:
      - cosmo
      - brand
    css: styles.css

execute:
  freeze: auto

bibliography: references.bib
csl: harvard-manchester.csl
link-citations: true